apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: environments.devconsole.openshift.io
spec:
  group: devconsole.openshift.io
  names:
    kind: Environment
    listKind: EnvironmentList
    plural: environments
    singular: environment
    shortNames:
      - env
  scope: Namespaced
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            type:
              type: string
              enum:
                - 'deploy'
#            cluster:
#              type: object
            namespace:
              type: string
  version: v1alpha1
