apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster
spec:
  # Add fields here
  kubernetesApiEndpoints:
    serverEndpoints:
      - clientCIDR: "0.0.0.0"
        serverAddress: "127.0.0.1"
  authInfo:
    controller:
      kind: Secret
      name: clustertokens/dsaas-stg
      namespace: sre