apiVersion: devconsole.openshift.io/v1alpha1
kind: Environment
metadata:
  name: example-environment
spec:
  # Add fields here
  type: 'deploy'
  namespace: 'myproject'
  clusterRef:
    kind: Cluster # this must be Cluster
    name: dsaas-stg # this must match the name of the Cluster you wish to point to
    apiGroup: devconsole.openshift.io
